<?php
    $date = new DateTime($post['date_crea']);
    $date_crea = $date->getTimestamp();
    $date = new DateTime($post['date_modif']);
    $date_modif = $date->getTimestamp();
?>
<div class="post">
    <h2>
        <?= $post['title']; ?>
    </h2>
    <p>
        Post créé le <?= date('d/m/Y', $date_crea); ?>
        <?= $date_modif?', modifié le '.date('d/m/Y', $date_modif):''; ?>
    </p>
    <p>
        <?= $post['content']; ?>
    </p>
    <p>
        Auteur : <?= $post['user']; ?>
    </p>
</div>